# Generated by Django 3.1.7 on 2021-03-11 15:34

from django.db import migrations


def create_profiles_to_users(apps, schema_editor):
    User = apps.get_model('authentication', 'User')
    Profile = apps.get_model('user_profile', 'Profile')
    for user in User.objects.all():
        try:
            user.profile
        except:
            Profile.objects.create(user=user)


class Migration(migrations.Migration):
    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(create_profiles_to_users),
    ]
